pipeline {

  agent any

  stages {
    stage('run Newman tests') {
      steps {
        sh 'newman run postman/create_user_collection.json -e postman/prod.postman_environment.json --reporters cli,junit,htmlextra --reporter-junit-export "newman_result.xml" --reporter-htmlextra-export "newman_result.html" '
      }
    }

  }
  post {
    always {
      junit "*.xml"
      publishHTML target: [
        allowMissing: false,
        alwaysLinkToLastBuild: false,
        keepAll: true,
        reportDir: '.',
        reportFiles: 'newman_result.html',
        reportName: 'Newman HTML Reporter'
      ]
    }

  }
}